### ISSUE TITLE
QTextEdit causes Memory and Performance issues

### ISSUE THREAD

**Issue by alopatindev** [alopatindev/qdevicemonitor#1]
QTextEdit has two unresolved issues (seem to be existing for a long time; so it's probably hard to fix):
1. It's slow (especially when dealing with long paragraphs)
2. It has a memory leak

Possible solution would be rewrite the whole front-end in HTML/CSS and JavaScript (and probably with WebSocket).
For me [this dirty experiment](https://gist.github.com/alopatindev/17a39fce20049989a0e4b63f002ac2c2/) works perfect with QtWebEngine: it's fast and doesn't leak.

I don't mean that QtWebEngine should be used at all, it's better to have the whole UI accessible with any web browser (that will let the program keep starting fast and consume less memory).

As I'm not motivated to work on that I'm not going to touch it.
If you are interested in contributing this change—you are welcome: I'll assist you with some mentoring to solve this.
Thanks.

**Comment by WakeRealityDev** [comment]
The memory leak / perofrmance leak of QTextEdit may have been corrected in QT 5.9 https://bugreports.qt.io/browse/QTBUG-61137

**Comment by alopatindev** [comment]
Thanks! It might be a different bug, but anyway, right now it doesn't reproduce for me with Qt 5.7.1 on Gentoo GNU/Linux (not sure about other platforms).
